repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-case-conflict
  - id: check-executables-have-shebangs
    files: \.sh
  - id: check-json
  - id: check-vcs-permalinks
  - id: check-yaml
  - id: check-ast
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.13.0
  hooks:
  - id: pretty-format-yaml
    exclude: ^helm
    args: [--autofix, --indent, '2']
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v3.1.0
  hooks:
  - id: prettier
- repo: local
  hooks:
  - id: eslint
    name: ESLint
    entry: .bin/eslint.sh
    language: script
    files: ^.*\.(js|ts)$
    verbose: true
    pass_filenames: true
  - id: knip
    name: knip
    entry: .bin/knip.sh
    language: script
    verbose: true
    pass_filenames: false
