name: Setup Tools
description: Install and configure required tools in the workspace

runs:
  using: composite
  steps:
  - name: Setup ASDF Tools
    uses: egose/actions/asdf-tools@11b2fdce26a6e31253205396a31403c89ff492df

  - name: Install Python Requirements
    run: |
      pip install -r requirements.txt
      asdf reshim python
    shell: bash
