name: Setup Tools
description: Install and configure required tools in the workspace

runs:
  using: composite
  steps:
  - name: Install System Dependencies
    run: |
      sudo apt-get update -y
      sudo apt-get install -y \
        build-essential \
        libssl-dev \
        zlib1g-dev \
        libncurses5-dev \
        libncursesw5-dev \
        libreadline-dev \
        libsqlite3-dev \
        libgdbm-dev \
        libdb5.3-dev \
        libbz2-dev \
        libexpat1-dev \
        liblzma-dev \
        tk-dev \
        libffi-dev
    shell: bash

  - name: Setup ASDF Tools
    uses: egose/actions/asdf-tools@0c63eae5ec430443674adb1324ee68d88723b013

  - name: Install Python Requirements
    run: |
      pip install -r requirements.txt
      asdf reshim python
    shell: bash
