name: Setup Tools
description: Install and configure required tools in the workspace

runs:
  using: composite
  steps:
  - name: Setup ASDF Tools
    uses: egose/actions/asdf-tools@7d086a95ed095cdaea2c16e7e83676e708800d06

  - name: Install Python Requirements
    run: |
      pip install -r requirements.txt
      asdf reshim python
    shell: bash
