name: Setup Tools
description: Install and configure required tools in the workspace

runs:
  using: composite
  steps:
  - name: Setup ASDF Tools
    uses: egose/actions/asdf-tools@19b25f30dd4ebb3dd8e63694fedafa70803c1b6b

  - name: Install Python Requirements
    run: |
      pip install -r requirements.txt
      asdf reshim python
    shell: bash
