name: Setup Tools
description: Install and configure required tools in the workspace

runs:
  using: composite
  steps:
  - name: Setup ASDF Tools
    uses: egose/actions/asdf-tools@53b95f40ba39c1b460ad6ab6f6ccdb38cc8a9695

  - name: Install Python Requirements
    run: |
      pip install -r requirements.txt
      asdf reshim python
    shell: bash
