name: Setup Tools
description: Install and configure required tools in the workspace

runs:
  using: composite
  steps:
  - name: Setup ASDF Tools
    uses: egose/actions/asdf-tools@badb0f679e1baa1628818fad29cfd73f8222d49d

  - name: Install Python Requirements
    run: |
      pip install -r requirements.txt
      asdf reshim python
    shell: bash
