name: Test

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-app:
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    steps:
    - uses: hmarr/debug-action@f7318c783045ac39ed9bb497e22ce835fdafbfe6
    - uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb

    - name: Setup Tools
      uses: ./.github/actions/setup-tools

    - name: Setup NPM Packages
      uses: ./.github/actions/setup-yarn

    - name: Run App build
      run: npm run build

  pre-commit:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
    - uses: hmarr/debug-action@f7318c783045ac39ed9bb497e22ce835fdafbfe6
    - uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb

    - name: Setup Tools
      uses: ./.github/actions/setup-tools

    - name: Setup NPM Packages
      uses: ./.github/actions/setup-yarn

    - name: Rerun Pre-Commit Hooks on CI
      run: |
        pre-commit run --config=.pre-commit-config.yaml --color=always --show-diff-on-failure --all-files
