name: Setup NPM Packages
description: Setup required NPM packages

runs:
  using: composite
  steps:
  # See https://github.com/actions/cache/blob/main/examples.md#node---yarn
  - name: Get yarn cache directory path
    id: yarn-cache-dir-path
    run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
    shell: bash

  - uses: actions/cache@7921ae235bdcb376cc8f22558dc5f8ddc3c3c2f9
    with:
      path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
      key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      restore-keys: |
        ${{ runner.os }}-yarn-

  - name: Install NPM dependencies
    run: yarn
    shell: bash
